DATASET:
  TRAIN_PATH: "./data/BCSS_small/train"
  TEST_PATH: "./data/BCSS_small/test"
  IMAGE_FORMAT: ".png"

SAM:
  CHECKPOINT: "./model_checkpoint/sam_vit_b_01ec64.pth"
  RANK: 512

TRAIN:
  BATCH_SIZE: 2
  NUM_EPOCHS: 2
  LEARNING_RATE: 0.0001
